### ISSUE TITLE
Port Jared's NLP SQL to FunSQL to populate note_nlp

### ISSUE THREAD

**Issue by kzollove** [TuftsCTSI/TRDW.jl#73]
Port from SQL to FunSQL (if valuable).
Document this.

Mirror the way OHNLP does things.

**Comment by clarkevans** [comment]
Bridge2AI  will need note processing for its 2k initial population

**Comment by kzollove** [comment]
Work has started in ResearchRequests https://github.com/TuftsCTSI/ResearchRequests/commit/fdd804bf78c5a695457526979129d3c0620f4384

**Comment by kzollove** [comment]
Completed in https://github.com/TuftsCTSI/ResearchRequests/commit/fdd804bf78c5a695457526979129d3c0620f4384

**Comment by clarkevans** [comment]
We'll leave this project as-is, then evaluate in various research requests by copy/paste.
