### ISSUE TITLE
add to profile.jl

### ISSUE THREAD

**Issue by kzollove** [TuftsCTSI/TRDW.jl#79]
Wait until connect-macro is merged before work begins

- define_profile should include name and PCP
- make a new define_* function to capture first and last concept name and date from a funsql pair. This could be useful as a free service for many researchers
- make a new define_* function for measurements. Same as above but includes value_as_number... might also need a value_as_concept flavor

See Extract section of [this notebook](https://trdw-rdr.tuftsmedicine.org/notebooks/59854_Kryzanski_Spinal_Anesthesia/discover.html) for demo of last two

**Comment by clarkevans** [comment]
@xitology : Kyle had some ideas for expanding define functions
